### ISSUE TITLE
Polish version

### ISSUE THREAD

**Issue by Saguro** [DigglesMods/RareResources#1]
`Error(3870):unknown class:
Kohle_
    while executing
"get_class_category $name"
    (procedure "MakeTTEntry" line 2)
    invoked from within
"MakeTTEntry $ttfile $item $materials $tools [list $cn] $attribs"
    ("foreach" body line 40)
    invoked from within
"foreach item $items {
			#	log "  Item: $item\n";
				if {[string first [get_class_type $cn] "productionstoreenergyprotection"]!=-1&&[string first $cn..."
    ("foreach" body line 11)
    invoked from within
"foreach cn [ClassList] {
	#log "Class: $cn\n";
	if { ![regexp {^CObj*|^CTclRoot*} $cn] } {
		# log "Testing Class: $cn\n";
		set fail [catch {
			set ...":

proc MakeTTEntry {file name materials tools places attribs} {
	set category [get_class_category $name]
	set type [get_class_type $name]
	set era [get_class_era $name]
	set flags [get_class_flags $name]

	puts $file "{\n$name $category $type $era $flags\n"
	puts $file "// Materials\n{$materials}"
	puts $file "// Tools\n{$tools}"
	puts $file "// Places\n{$places}"
	puts $file "// Attribs\n{$attribs}"
	puts $file "}\n"
}

proc MakeExpEntry {file attribs atrlst} {
	set bitwert 0
	for {set i 0} {$i<[llength $atrlst]} {incr i} {
		if [string match "*[lindex $atrlst $i]*" $attribs] {
			set bitwert [expr int($bitwert+pow(2,$i))]
		}
	}
	set firstwert $bitwert
	if {2<[llength $attribs]} {
		for {set i 0} {$i<[llength $atrlst]} {incr i} {
			if {int(pow(2,$i))&$firstwert} {
				lappend bitwert [expr int(pow(2,$i))^$firstwert]
			}
		}
	}
	if [string index $bitwert 0] {
		foreach nextwert $bitwert {
			seek $file 0 start
			if {-1==[lsearch [gets $file] $nextwert]} {
				seek $file 0 end
			 puts -nonewline $file "$nextwert "
			}
		}
	}
}

set ttfile [open "data/scripts/gameplay/gen_tt.tcl" w]
set expfile [open "data/scripts/gameplay/gen_exp.lst" w+]
puts -nonewline $expfile "1 2 4 8 16 32 64 128 "
set explst "[get_expattrib 0] atr_Kampf"

# [catch {}] == 0 -> okay
foreach cn [ClassList] {
	#log "Class: $cn\n";
	if { ![regexp {^CObj*|^CTclRoot*} $cn] } {
		# log "Testing Class: $cn\n";
		set fail [catch {
			set items [call_method_static $cn prod_items]
		}]
		if {$fail==0} {
			# log "Techtree Class: $cn\n";
			# log "$cn    $items\n";
			foreach item $items {
			#	log "  Item: $item\n";
				if {[string first [get_class_type $cn] "productionstoreenergyprotection"]!=-1&&[string first $cn "Zelt"]==-1} {
					set tttsection_tocall $item
					call scripts/misc/techtreetunes.tcl
					set materials [subst \$tttmaterial_$item]
					set tools [subst \$tttinfluence_$item]
					set attribs [subst \$tttinvent_$item]
					catch {unset tttmaterial_$item tttinvent_$item tttgain_$item tttinfluence_$item}
					catch {unset tttpreinv_$item tttitems_$item}
					catch {unset tttenergycons_$item}
					catch {unset tttenergyrange_$item tttenergyvalue_$item tttenergystore_$item tttenergyminstore_$item tttenergyyield_$item}
					catch {unset tttnumber2produce_$item}
				} else {
					set materials [call_method_static $cn prod_item_materials $item]
					set tools [list]
				#	log "    materials: $materials\n";
					if { [check_method $cn prod_item_attribs] } {
						set attribs [call_method_static $cn prod_item_attribs $item]
					} else {
						set attribs [list]
					}
				}
	
	
				set matlist $materials
				set materials ""
				set donelist ""
				foreach mattype $matlist {
					if {[lsearch $donelist $mattype] < 0} {
						lappend donelist $mattype
						foreach listitem $matlist {
							if {$listitem == $mattype} {
								lappend materials $listitem
							}
						}
					}
				}
	
				MakeTTEntry $ttfile $item $materials $tools [list $cn] $attribs
				MakeExpEntry $expfile $attribs $explst
	
			}
		}
	}
}

close $ttfile
seek $expfile 0 start
log "[llength [gets $expfile]] Attributkombinationen zum Erfinden nötig!"
close $expfile

unset attribs materials tools fail item cn tttsection_tocall ttfile expfile explst

Error(3019):unknown class:
Kohle_
    while executing
"get_class_category $name"
    (procedure "MakeTTEntry" line 2)
    invoked from within
"MakeTTEntry $ttfile $item $materials $tools [list $cn] $attribs"
    ("foreach" body line 40)
    invoked from within
"foreach item $items {
			#	log "  Item: $item\n";
				if {[string first [get_class_type $cn] "productionstoreenergyprotection"]!=-1&&[string first $cn..."
    ("foreach" body line 11)
    invoked from within
"foreach cn [ClassList] {
	#log "Class: $cn\n";
	if { ![regexp {^CObj*|^CTclRoot*} $cn] } {
		# log "Testing Class: $cn\n";
		set fail [catch {
			set ..."
    invoked from within
"call scripts/init/makettree.tcl":
log "parse systeminit script"
log "minimal:[minimalrun]"

# log_mask -* +system +tclerror +gui

;# logmod Tcl								;# print only Tcl logs
logdebug off

if { ![minimalrun] } {
call scripts/init/customcommands.tcl
}

set info "[lmsg Language] Full version"
log "Loading $info"
set_run_info $info

;# useful procedures
proc ? { args } { print [eval {$args}] }

call scripts/init/shader.tcl
call scripts/init/txtinit.tcl
call scripts/init/animinit.tcl
call scripts/init/classinit.tcl
load_info "[lmsg "Classes done"]"

if { ![minimalrun] } {
call scripts/init/soundinit.tcl
load_info "[lmsg "Soundinit done"]"
call scripts/init/adaptiveinit.tcl
load_info "[lmsg "Musicinit done"]"

call scripts/init/lginit.tcl
load_info "[lmsg "LGInit done"]"

call scripts/init/talkinit.tcl

call scripts/init/claninit.tcl

call scripts/init/makettree.tcl
init_techtree scripts/gameplay/gen_tt.tcl
load_info "[lmsg "Techtree done"]"
}

if { ![minimalrun] } {
call scripts/init/fight.tcl
load_info "[lmsg "Fightinit done"]"
}

#log "initializing artificial inteligence"
ai init 0 data/scripts/ai/std_ai.tcl
set aideflevel [perfoptions playeraidefault]
if { $aideflevel != 0 } {
	log "ai enabled"
	ai enable 0
}
#log "AI initialized"

;# create map and excute procedure gameinit
# map create 128 128 {  }
map create 64 64 {  }

# call data/gamesave/preset_Urwald.tcl
# call data/gamesave/preset_Urwald_a.tcl

if { [file exists data/userstartup.tcl] } {
	call userstartup.tcl
} else {
	if { ![minimalrun] && ![get_mapedit] } {
		call data/templates/unq_menue.tcl
		MapTemplateSet 25 28

	        call templates/urw_gng_021_a.tcl
	        MapTemplateSet 21 40

	        call templates/urw_gng_022_a.tcl
	        MapTemplateSet 45 40

	    	set_view 32.368 40.858 1.38 -0.355 0.165		;# set inital camera view (x y zoom)
	    	sel /obj
			set FR [new FogRemover]
			set pos { 32.368 39.5 10 }
			set_pos $FR [vector_add $pos {0 0 0}]
			call_method $FR fog_remove 0 50 50
			call_method $FR timer_delete -1
			adaptive_sound marker menue $pos
			adaptive_sound primary menue

	    	sel /obj
	    	set ts [new Trigger_StartScreen]
	    	call_method $ts validate
	    	call_method $ts disable_logging

	} else {
		perfoptions simplecontrol 0
	}
   	gui_new_game
}

show_loading no
gametime start
load_done
log "systeminit script succesfully parsed"

`

**Comment by Saguro** [comment]
Zip file
[Seltene Ressourcen.zip](https://github.com/DigglesMods/RareResources/files/2217307/Seltene.Ressourcen.zip)

**Comment by cech12** [comment]
Thanks for your submission.
I analysed the files and there are no differences in the file content except the messages.txt file, which should not cause this error.

The only difference is, that the files of the polish version are written in capital letters. This is interesting and was not included in the DigglesModManager. 
I fixed this in this commit: https://github.com/DigglesMods/DigglesModManager/commit/8503c88674a93b84c5bffc01e2ca8a6ee7f87237

I will edit the change of the messages.txt and add the polish translation. :)

**Comment by cech12** [comment]
I added the polish translation to the messages.txt here: https://github.com/DigglesMods/RareResources/commit/9b224a617ec3817dfbe20aef286bff41560bb1ba

At next release this mod should work with the polish version.

**Comment by cech12** [comment]
Hey @Saguro 

we found out, that we need the directory **Wiggles\Data\Scripts\text\doc** of your polish game version to fix some issues. It would be nice, if you add a zip-file of this directory to this issue here. Thanks!

**Comment by Saguro** [comment]
here is my **doc** folder :)
[doc.zip](https://github.com/DigglesMods/RareResources/files/2301980/doc.zip)

**Comment by cech12** [comment]
Hey! Thanks for your upload! :)
I have changed the mods: ProductionStatistics, StoneDoor, DwarfStatistics, Barrow, RareResources, PowerPotion, SwitcherGeneratorDungeon and BugFix.
All these mods now have a **Data\Scripts\text\doc\pl** directory. So if you want to test the mods, please download these directories and put them to your downloaded mod and install them with the DigglesModManager. 
After that you should recognize changes at the production and dwarfs statistics. And in the F1 menue, there should be the game manager of the SwitcherGeneratorDungeon mod. 
I have not release the new version yet, because the changes are not tested.

**Comment by Saguro** [comment]
hi, i just tested them and:
DwarfStatistics works great
ProductionStatistics - some things arent translated  (90% is in polish, but
rest is in english or german), also i would recommend or suggest to put
there something that hides resources that i dont need (on image we can see
a lot of coal, a lot of crystal, gold, food etc, so it would be nice if i
could hide it using combobox)
SwitcherGeneratorDungeon - works
StoneDoor and PowerPotion - can u tell me the codes (hacks) to get building
of that? i dont want to start over and invent these (i'm in campaign)
Barrow - i dont really uderstand it. can u explain me what that mod do?
send images of it?

also in ModManager i have errors (on pic)
[image: error.png]
[image: production.png]

wt., 21 sie 2018 o 11:08 cech12 <notifications@github.com> napisał(a):

**Comment by cech12** [comment]
Hey! Sorry for the late answer.

Sorry, but I cannot see any picture you add to your post here. 

ProductionStatistics : 
- The missing translation could be fixed if you can translate the words for me :D 
- You can interact with the resources you can see there. You can add tasks to your wiggles without interrupt its current task. I do not understand what you want to hide. (Maybe it is why I cannot see the image^^)

StoneDoor: You can produce it in the Stonecutter. But if you already started a game it could be, that it is not there. You can test to build a new Stonecutter. Or you start a new game for testing.

PowerPotion: You can produce it in the Brewery. But if you already started a game it could be, that it is not there. You can test to build a new Brewery. Or you start a new game for testing.

Barrow: This mod adds a Barrow to the game. You can produce it in the Sawmill. When a Wiggle has a barrow in its inventory, there are 6 more inventory slots (like the pannier) aditionally to the pannier slots.

Could you send me the images?

**Comment by Saguro** [comment]
[image: error.png]
[image: production.png]

czw., 30 sie 2018 o 10:15 cech12 <notifications@github.com> napisał(a):

**Comment by Saguro** [comment]
i though i was sending an email, but it was a topic in github :v (my replies come from gmail)
here are images

![error](https://user-images.githubusercontent.com/41551039/44864629-6b40cb80-ac80-11e8-9dbb-6ce8ea4868eb.png)
![production](https://user-images.githubusercontent.com/41551039/44864630-6bd96200-ac80-11e8-9785-3acac170b92c.png)

**Comment by cech12** [comment]
Hey! 
No Problem ;)

Ok, these errors occur, when there is no _config.json_ file in the mod directories. Are you sure, that you downloaded and unziped the mods correctly?

The big item list is caused by the amount of items you have.^^ So that is an other issue.

**Comment by Saguro** [comment]
In the evening I will try install mods again.

That's what I wanted to say. It would be nice if there was an option to
hide/unhide some kinds of items, but it's only my suggestion :)

pon., 3.09.2018, 11:04 użytkownik cech12 <notifications@github.com> napisał:

**Comment by cech12** [comment]
> That's what I wanted to say. It would be nice if there was an option to hide/unhide some kinds of items, but it's only my suggestion :)

That is another issue and has nothing to do with the polish translation. You can open an issue for ProductionStatistics mod, and explain your wishes. 

> ProductionStatistics - some things arent translated (90% is in polish, but rest is in english or german)

Can you show (screenshots) and translate the missing words? 

> StoneDoor: You can produce it in the Stonecutter. But if you already started a game it could be, that it is not there. You can test to build a new Stonecutter. Or you start a new game for testing.

Does this mod work?

> PowerPotion: You can produce it in the Brewery. But if you already started a game it could be, that it is not there. You can test to build a new Brewery. Or you start a new game for testing.

Does this mod work?

> Barrow: This mod adds a Barrow to the game. You can produce it in the Sawmill. When a Wiggle has a barrow in its inventory, there are 6 more inventory slots (like the pannier) aditionally to the pannier slots.

Does this mod work?

> In the evening I will try install mods again.

Could you fix the problems with the 2 mods FixWiggles and BetterStorage? (Note: The WigSound mod is actually not really a mod for the DigglesModManager)

**Comment by cech12** [comment]
Hey, I published a new version of the DigglesModManager. Would you be so nice and try the mods? :D

**Comment by Saguro** [comment]
hi,
do i need to start a new game to check if storage has new options, and
other building got new items to craft?
I have started a game and voice works perfectly (the elf and wiggles
actually talks in polish in cutscenes!), i changed the clan and it also
works.
I found the production in menu seems to wrok, but the other things in menu
arent.
The family tree is blank, same to diary, help and dwarves. at the top i see
the information "go find 6 rings" (in polish) but nothing in diary. i cant
get to dwarf by a menu option where it is also blank (i will attach a photo
with a tree of technology, and the second one where it used to be list of
dwarfs (karły means dwarfs)).
when i press on something in tree of technology (for example tent) i do not
get any ifnormation about it as i used to do.

I'm not sure if on that version of wiggles i have installed fixes or its
raw old version, but i will try to do something with it and try other
options. Also if u have got a cheats (to spawn building) or saves with
technology of improved buildings i would be able to check if all new stuff
works.

Anyway great work! Thanks!
[image: image.png]
[image: image.png]

czw., 14 mar 2019 o 15:05 cech12 <notifications@github.com> napisał(a):

**Comment by cech12** [comment]
Hey Saguro!
To test that all mods are working it is recommended, that you start a new game. ;) 

I hope I understand you correctly. You have installed the new DigglesModManager and activated all mods. You set an other clan in the ChangeCampaignClan mod. You started a new campaign and the clan was changed. So the ChangeCampaignClan mod works. 

The ProductionStatistics mod works, too, because you see the new menu.

For the listed problems it would be nice, when you check, if this is working without installed mods. If not, please reinstall the game and install the mods after all other things are working. 

When you activate the console for the game, you can spawn buildings and other things with the following command
`qnew Lager`
This spawns a Storage (Lager) at the pointers position. If you want to spawn other things, here is a list of the names: https://wiggles.ruka.at/forum/viewtopic.php?t=2

p. s.: Sorry, but the images are missing. ;)

**Comment by Saguro** [comment]
hi. i have changed pc and installed raw version of wiggles on it to check
what is going on. the game is starting but i got a problem right after it -
my mouse is like out of the game - i mean i'm in the menu of game and after
first 2 second the mouse in game (that hand) stops to move and it seems
like i'm on deskopt. after getting back to the game with Alt+TAB i' able to
move mouse in game for about 1.5 cm and again mouse of game stops to listen
me and i'm "on" deskopt. i have tried to install german, english versions,
installed patches etc tried to do anything but it seems like my pc is not
letting me to stay in game window. Have u had a problem like that?

pt., 15 mar 2019 o 09:42 cech12 <notifications@github.com> napisał(a):

**Comment by cech12** [comment]
Hey, that is weird. I never heard of a problem like this. Maybe it is a graphical issue. Please test the fixes of the installation video and the fixes in the comments below the video.

**Comment by Saguro** [comment]
hi, i have tested them and still its not working. the problem is that i
have a game in a window and after a second my pc loses the "focus" on the
game like i have pressed the windows button and i' able to move windows
cursor, and do stuff on others windows (chrome for example). The same game
folder i used to have on old pc and i put it on friends laptop and its
working. i havent activated my windows license (my university needs to
recover its license) but i dont think thats a problem.

Do i need any programs to make wiggles work? like directx or smth like
that? maybe i'm missing something since the system is new.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

wt., 26 mar 2019 o 10:45 cech12 <notifications@github.com> napisał(a):

**Comment by cech12** [comment]
Hey, 

sorry, that you have these problems with the game .Found after googling your problem: Maybe another program in background is running and pulls the focus. Please test to press Alt-F4  immediatly when the focus is out of the game to exit the background process. (Maybe more than once) 
After that, you should be able to play the game.

If that does not work, please google. That is not a Diggles or Mod Issue.

**Comment by cech12** [comment]
I think, this issue can be closed after 2 years of inactivity.
